version: '3.8'

services:
  web1:
    build: .
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    expose:
      - "5000"
    depends_on:
      - db
      - redis

  web2:
    build: .
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    expose:
      - "5000"
    depends_on:
      - db
      - redis

  web3:
    build: .
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    expose:
      - "5000"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
      - web3

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurante
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
